[package]
name = "arustid"
version = "0.1.0"
authors = ["Simon Andersson <simon.asker@posteo.net>"]
description = "Generates fractals based on L-Systems using Turtle graphics"

[dependencies]
clap = "2.23"

[dependencies.sdl2]
version = "0.29"
default-features = false
features = ["gfx", "image"]
