[package]
name = "arustid"
version = "0.1.0"
authors = ["Simon Andersson <simon.asker@posteo.net>"]

[dependencies]

[dependencies.sdl2]
version = "*"
default-features = false
features = ["gfx", "image"]
